### ISSUE TITLE
remove messages in groups

### ISSUE THREAD

**Issue by dvoris** [steavy29/Telegram.Net#10]
у клиента не хватает метода для удаления сообщений в группе/супергруппе (при наличии статуса администратора).
добавьте, пожалуйста)

**Comment by steavy29** [comment]
will do

**Comment by steavy29** [comment]
Added request. See `DeleteMessages` in `TelegramClient`. It accepts list of message ids that has to be deleted and returns list of message ids that actually were deleted on server.
