### ISSUE TITLE
Try to load history for contact, Telegram returns null

### ISSUE THREAD

**Issue by TheBottleGit** [steavy29/Telegram.Net#12]
It returns null, but i have messages in telegram
There is project, session dat inside : http://rgho.st/6kbJnBSsf

**Comment by steavy29** [comment]
Can you, please, show some of your code here? How do you load history?

**Comment by TheBottleGit** [comment]
http://pastebin.com/Vbd0Mu9w

**Comment by TheBottleGit** [comment]
Major Bug!

**Comment by TheBottleGit** [comment]
fixed by MessagesMessagesSliceConstructo, add to readme,

Thank you. Add please Donations, i will pay you.

**Comment by steavy29** [comment]
Glad it helped.
There will be no donations section in this project. I believe Github isn't about this :)
