### ISSUE TITLE
In fced58a you forget about  FileSessionStore in Session.cs

### ISSUE THREAD

**Issue by TheBottleGit** [steavy29/Telegram.Net#14]
In fced58a you forget about  FileSessionStore in Session.cs

**Comment by steavy29** [comment]
Actually I intentionally removed it. Here is the motivation:
I think this `FileSessionStore` is quite situational. In different cases you would like to have your own implementation of session storing. F.e. on mobile device(crossplatform support is in my goals list) you'll want one implementation, on windows machine - other.
Also its very likely that one will want to tweak storing mechanism.
So I decided to move `FileSessionStore` to `Tests` project, where it is used. And everyone should implement his own version of session store.
