### ISSUE TITLE
Add Method messages.botCallbackAnswer

### ISSUE THREAD

**Issue by TheBottleGit** [steavy29/Telegram.Net#17]
I can't do this, can you help me with this?

https://github.com/sochix/TLSharp/blob/master/TeleSharp.TL/TL/Messages/TLRequestGetBotCallbackAnswer.cs

**Comment by TheBottleGit** [comment]
![image](https://cloud.githubusercontent.com/assets/13104180/19839531/d50e4542-9f0d-11e6-8c63-365288858442.png)
I do this with `messages.botCallbackAnswer#b10df1fb flags:# alert:flags.1?true has_url:flags.3?true message:flags.0?string url:flags.2?string = messages.BotCallbackAnswer;`
But I do not know does it work

**Comment by steavy29** [comment]
This request class is from higher Api Level Protocol, which is not yet supported here, so it won't work. Support of the latest Api Level is on the tasks list but probably won't be added sooner that one or two weeks.

**Comment by TheBottleGit** [comment]
Okay, thx. I be waiting.
