### ISSUE TITLE
Error when trying to send a message

### ISSUE THREAD

**Issue by SergeyIvann** [steavy29/Telegram.Net#24]
Hello,

I am trying to send a message to a telegram bot using the following code:

       public async Task SendMessageByUserName(TelegramClient client, string command)
        {
            var user = await client.ResolveUsername(userName) as UserForeignConstructor;
            var peer = new InputPeerForeignConstructor() { userId = user.id };
            var message = await client.SendMessage(peer, command);
        }

I am getting the following error: {"BadRequest - PEER_ID_INVALID"}
Would you please clarify what I am doing wrong?

I also see that there is the second parameter in the InputPeerForeignConstructor class (accessHash) but I am not sure how to get it and whether I need it.

Thanks

**Comment by SergeyIvann** [comment]
RESOLVED.
This is the correct code:
            var peer = new InputPeerForeignConstructor(user.id, user.accessHash);

**Comment by steavy29** [comment]
Yes, for such contracts you should use constructors, they'll give you a correct list of fields needed for creation. Empty constructors are mainly supported for internal needs like object creation via reflection.
