### ISSUE TITLE
How can i receive a message

### ISSUE THREAD

**Issue by wasimjee** [steavy29/Telegram.Net#25]
How can i receive a message from users

**Comment by steavy29** [comment]
You should create an instance of `TelegramClient`, subscribe to appropriate `Update` event and then invoke `Start` method. Afterwards all messages will be propagated through `Update` event.

**Comment by steavy29** [comment]
I'll be able to get you sample of code in the evening. But the main idea is that you subscribe to `UpdateMessage` event and then `if\else` on type of `Updates` object. To know what could be there see descendants of `Updates` class. Generally it should reflect these types from the documentation https://core.telegram.org/type/Updates

**Comment by wasimjee** [comment]
@steavy29 Thank you very much , i will be waiting for a sample.

**Comment by steavy29** [comment]
Subscribe to event            
            `client.UpdateMessage += UpdateMessage;`

Handle update event

            private void UpdateMessage(object sender, Updates update)
            {
                switch (update.Constructor)
                {
                    case Constructor.updatesTooLong:
                    {
                        // need to download updates manually
                        break;
                    }
                    case Constructor.updateShortMessage:
                    {
                        var upd = update as UpdateShortMessageConstructor;
                        // upd.message
                        break;
                    }
                    case Constructor.updates:
                    {
                        var upd = update as UpdatesConstructor;
                        foreach (var updatePiece in upd.updates)
                        {
                            // handle update
                        }
                        break;
                    }
                }
                // ...
            }
