### ISSUE TITLE
AUTH_KEY_UNREGISTERED.

### ISSUE THREAD

**Issue by elyfran** [steavy29/Telegram.Net#3]
Now that this problem: AUTH_KEY_UNREGISTERED.
I am using the method : ImportContactByPhoneNumberAndSendMessage.

if I try to use the method 'MakeAuth' is again generated an exception:

An exception of type 'System.IO.EndOfStreamException' occurred in mscorlib.dll but was not handled in user code

**Comment by steavy29** [comment]
Before reauthenticating try deleting your session file.
I tried this test both with your config and my own and it worked well.

If problem will still reproduce after deleting sesion file, please show me full stacktrace or some more info so that I could reproduce it.

**Comment by steavy29** [comment]
Hey. I think I've fixed it. Can you check. Make sure to delete your `session.dat` file to make sure you are not testing against old config.

**Comment by elyfran** [comment]
First thanks for the support the resolutions of these problems.

after I tested two different methods the problem occurred below.
- MessageSeqNoTooLow - 


and if I try to use connect ( true) the error is triggered : AUTH_KEY_UNREGISTERED

**Comment by steavy29** [comment]
I'm currently working on handling of this error(`MessageSeqNoTooLow `). As a temprary solution you should delete your `session.dat`

**Comment by elyfran** [comment]
where i found this file?

**Comment by steavy29** [comment]
Near your executable. In case of Tests - Tests/bin/Debug(Release)

**Comment by elyfran** [comment]
yeah!!! nice =D thx again
