### ISSUE TITLE
Sending Audio and Video

### ISSUE THREAD

**Issue by wasimjee** [steavy29/Telegram.Net#31]
How can we send audio and Video to a message

**Comment by steavy29** [comment]
At first you need to upload the file to telegram server with an appropriate method and then create and send message with Media of corresponding type using uploaded file handle.

**Comment by wasimjee** [comment]
@steavy29 , is there any sample for that

**Comment by steavy29** [comment]
Have a look in tests where Image message is sent. It should be pretty the same: upload file and use appropriate media constructor.

**Comment by wasimjee** [comment]
Thanks @steavy29 , i have no issue in image, just with Video and Audio,

**Comment by steavy29** [comment]
Could you please describe a bit how Video and Audio is different from Image for you?

**Comment by wasimjee** [comment]
when i uploaded video, and send the message, i just recieved the screenshot of video as an image.

**Comment by steavy29** [comment]
Could you please show your sample of code?

**Comment by wasimjee** [comment]
I am out right now. Will send in few hours
