### ISSUE TITLE
How to mark a message as read? 

### ISSUE THREAD

**Issue by romi4rd1** [steavy29/Telegram.Net#33]
how a message has sent by contact make it as read (double check symbol) ?

**Comment by romi4rd1** [comment]
Solved,.. 
thx... @steavy29

**Comment by mirror-neuron** [comment]
@romi4rd1 why you not posted solution? I have same question.

**Comment by steavy29** [comment]
@mirror-neuron I've added ReceivedMessagesRequest to the library. So what you need is TelegramClient.SendRpcRequest and pass to it an instance of ReceivedMessagesRequest

**Comment by mirror-neuron** [comment]
@steavy29 thanks for quick reply, i guess your library better than TLSharp
