### ISSUE TITLE
got Error: Flood - FLOOD_WAIT_62720

### ISSUE THREAD

**Issue by romi4rd1** [steavy29/Telegram.Net#34]
That error raised causes by i have running 4 desktop application using same one loginNumber and online for more 2days.

How to resolve that error ?

**Comment by steavy29** [comment]
Hi. There is no straight way to solve this, since its limitation of Telegram itself and it occurs because you sent too many requests from the same login. So either limit your amount of requests or login with different users(credentials)

**Comment by romi4rd1** [comment]
i will try to reduce the limit of login.
Oke, thx for your description, @steavy29
