### ISSUE TITLE
DC Invalid when trying to download image

### ISSUE THREAD

**Issue by gviddy** [steavy29/Telegram.Net#36]
When I call GetFile() I am getting the following error.. It is an image that I am trying to download...

Throwing exception for request AuthExportAuthorizationRequest because of error BadRequest - DC_ID_INVALID

**Comment by steavy29** [comment]
Hi. Which session storage do you use? In-file?

**Comment by gviddy** [comment]
Yes, created a simple File Session Store....

**Comment by steavy29** [comment]
Did you try to clear it?

**Comment by gviddy** [comment]
I've deleted the app and deployed it brand new to the device. Would that be doing the same thing?

Do you think it's more to do with saving the file than the DC id being wrong somehow ?

**Comment by steavy29** [comment]
No, I'm just trying to collect more data on this - whether problem is in corrupted session file or in request itself. So it looks like to be a problem with request.

**Comment by gviddy** [comment]
Yes it fails in the following function.....

```
public async Task<UploadFileConstructor> GetFile(FileLocationConstructor fileLocation, int offset, int limit)
        {
            var request = new GetFileRequest(new InputFileLocationConstructor(fileLocation.volumeId, fileLocation.localId, fileLocation.secret), offset, limit);
            await SendRpcRequestInSeparateSession(fileLocation.dcId, request);

            // only single implementation available
            return (UploadFileConstructor)request.file;
        }
```

When it does the SendRpcRequest...... And then within that function it fails on the following line....

`await SendRpcRequest(exportAuthRequest);`

Unfortunately I just don't understand any of that RpcRequest stuff... so would be great to hear if you have any ideas what might be going wrong.....

**Comment by gviddy** [comment]
The error is: Throwing exception for request AuthExportAuthorizationRequest because of error BadRequest - DC_ID_INVALID

**Comment by steavy29** [comment]
Hi. Can you share your session.dat with me(in private) so that I could reproduce this issue?

**Comment by gviddy** [comment]
oh I am running on an Android device... I am not sure if that is possible ?

**Comment by steavy29** [comment]
If you're using FileSessionStore, then you should be able to find that file. Could you check please?

**Comment by gviddy** [comment]
yep, got it... how do I send it to you ?

**Comment by steavy29** [comment]
Please, find me in Telegram https://t.me/steavy29

**Comment by gviddy** [comment]
Please find attached my session.dat …..

 

Gerard.

**Comment by gviddy** [comment]
Yes, this has fixed the error.... thank you! 👍
