### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by a-rahmani1998** [steavy29/Telegram.Net#39]
hi , I start for use this library 
help for solve this error :
![bandicam 2017-09-18 11-02-06-728](https://user-images.githubusercontent.com/31850943/30556948-891a28c0-9c61-11e7-826d-cc2d18387e3f.jpg)

sample source code for winform , tnx

**Comment by steavy29** [comment]
Hi. This is a compilation error not related to the library. Your syntax is wrong. Try adding `return` statement in catch block either remove `try{} catch` at all.
