### ISSUE TITLE
Have somebody source with usage this library?

### ISSUE THREAD

**Issue by munrocket** [steavy29/Telegram.Net#41]
I think just throw link to https://core.telegram.org/schema not enoght. Maybe somebody have some open source project with this library? I want to understand how to recieve channel messages.

**Comment by steavy29** [comment]
It's not possible to handle channels in current version of the API.

**Comment by munrocket** [comment]
Your library clean and can mark message as read but can't read channels message.
TLSharp library can read channels message but need refactor and can't mark message as read.

LoL, why c# has such a pathetic telegram libraries? It's only one desktop language that I know well.
Maybe you know some telegram bot library that could help me or some exotic methods? Is layer 66 necessary for implementation marking message?

**Comment by munrocket** [comment]
>It's not possible to handle channels in current version of the API.

Sorry but i can't believe in this, maybe official manual outdated.

**Comment by munrocket** [comment]
Thanks, Mr. Steavy29. I solve my problem with special request in TLSharp library.

**Comment by steavy29** [comment]
I meant in "currently implemented" API version.
