### ISSUE TITLE
How Sochix telegram session convert to steave29?

### ISSUE THREAD

**Issue by InokentiyVas** [steavy29/Telegram.Net#43]
Sochix TLSharp sessions files session.dat to steave29 sessions.dat
I copy and start, but show error: "System.Exception: "Invalid constructor code 2E13F4C3"?
Help me steave, please!

**Comment by steavy29** [comment]
Hi. Are you in production with your session.dat? I suggest that you just relogin user and delete your old session.dat. And then have it generated again in Telegram.net. 
Please describe your case in more details.

**Comment by InokentiyVas** [comment]
I need to transfer the sessions of my project to the Layer 23. There is no possibility to create, is this possible?

**Comment by steavy29** [comment]
I'm not sure what this transferring means but you can reverse engineer structure of your current `session.dat` and the desired one and then implement your own ISessionStore where you'll read old session and then serialize in new format.

**Comment by InokentiyVas** [comment]
I'm trying to figure it out, but nothing comes in :(
https://github.com/sochix/TLSharp/blob/master/TLSharp.Core/Session.cs

**Comment by steavy29** [comment]
solved
