### ISSUE TITLE
 Enabling session after publication in IIS

### ISSUE THREAD

**Issue by elyfran** [steavy29/Telegram.Net#5]
After generating the " core.dll " as should be created " session.data " when you published the application in IIS ?

Because at this point I will have to inform the received code.

**Comment by elyfran** [comment]
I would like to inform the path of " session.data " ?

**Comment by steavy29** [comment]
When you create `FileSessionStore` you can configure path to your session file

**Comment by elyfran** [comment]
thx

**Comment by elyfran** [comment]
I can create a "session.dat" on a PC and use it in another?

**Comment by steavy29** [comment]
I don't see any reason why you can't do it.

**Comment by elyfran** [comment]
ok thx
