### ISSUE TITLE
Exception: MessageSeqNoTooLow

### ISSUE THREAD

**Issue by andrew-maksimov** [steavy29/Telegram.Net#9]
Passed tests:
AuthenticationWorks
DataCenterMigrationErrorHandling
TestConnection

All other tests - failed.

_____________________
Test Name:	AuthUser
Test FullName:	Telegram.Net.Tests.Tests.AuthUser
Test Source:	F:\Telegram\Telegram.Net-master\Telegram.Net.Tests\Tests.cs : line 72
Test Outcome:	Failed
Test Duration:	0:00:00,2725698

Result StackTrace:	
в Telegram.Net.Core.Requests.MTProtoRequest.ThrowIfHasError() в F:\Telegram\Telegram.Net-master\Telegram.Net.Core\Requests\MTProtoRequest.cs:string 59
   в Telegram.Net.Core.TelegramClient.<SendRpcRequest>d__46.MoveNext() в F:\Telegram\Telegram.Net-master\Telegram.Net.Core\TelegramClient.cs:строка 414
...
   в System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Result Message:	
Test method Telegram.Net.Tests.Tests.AuthUser threw exception: 
Telegram.Net.Core.TelegramReqestException: MessageSeqNoTooLow -

**Comment by steavy29** [comment]
`MessageSeqNoTooLow` means that your `Session` is out of sync and has to be recreated. I'm going to implement it this or next week.
As a temp fix you need to vipe your `session.dat` file
